# print("Hello")
from math import ceil


###########################################
###             CONVEX HULL             ###
###########################################

### Paint Blending ###
# Question # - Colour A = (10%, 30%) and colour B = (30%, 70%). Which of the following colours can you make? a. (40%, 70%)
# b. (60%, 20%) c. (40%, 90%) d. (25%, 60%)
# Hint - use weighted means

A1 = 10
A2 = 30
B1 = 40
B2 = 70

a = (1*A1 + 1* B1) / 2
print(ceil(a))
b = (1*A2 + 2*B2) / 3
print(ceil(b))

### Colour Space ###
# A new color can be produced by mixing two paints if and only if it, in the color-space, lies on the segment
# defined by the other 2 paints.
# A new color can be produced by mixing 3 paints if and only if it, in the color-space, lies in the triangle
# defined by their other 3 paints.
# The Mixture ratio is inversely determined by a geometric measure. Co-linear will be length of segment.
# Tri will be the area of the triangle formed.

# Question # - We now have three kinds of paint, which are U = (10%, 10%), V = (60%, 10%), W = (10%, 30%).
# Which of the following colors can't be generated by mixing these 3 kings of paint?